import scrapy


class ScraperSpider(scrapy.Spider):
    name = "scraper"
    allowed_domains = ["www.bikedekho.com"]
    # variants_links=["https://www.bikedekho.com/royal-enfield/scram/reviews","https://www.bikedekho.com/royal-enfield/classic-350/reviews","https://www.bikedekho.com/royal-enfield/hunter/reviews","https://www.bikedekho.com/royal-enfield/bullet-350/reviews","https://www.bikedekho.com/royal-enfield/continental-gt-650/reviews","https://www.bikedekho.com/royal-enfield/himalayan/reviews","https://www.bikedekho.com/royal-enfield/meteor/reviews","https://www.bikedekho.com/royal-enfield/interceptor-650/reviews","https://www.bikedekho.com/royal-enfield/super-meteor-650/reviews"]
    # for link in variants_links:

    # start_urls = ["https://www.bikedekho.com/royal-enfield/scram/reviews","https://www.bikedekho.com/royal-enfield/classic-350/reviews","https://www.bikedekho.com/royal-enfield/hunter/reviews","https://www.bikedekho.com/royal-enfield/bullet-350/reviews","https://www.bikedekho.com/royal-enfield/continental-gt-650/reviews","https://www.bikedekho.com/royal-enfield/himalayan/reviews","https://www.bikedekho.com/royal-enfield/meteor/reviews","https://www.bikedekho.com/royal-enfield/interceptor-650/reviews","https://www.bikedekho.com/royal-enfield/super-meteor-650/reviews"]
    # start_urls=['https://www.bikedekho.com/bajaj-bikes/bajaj-pulsar-200-ns/reviews', 'https://www.bikedekho.com/bajaj-bikes/pulsar-150/reviews', 'https://www.bikedekho.com/bajaj-bikes/pulsar-125/reviews', 'https://www.bikedekho.com/bajaj-bikes/pulsar-ns-125/reviews', 'https://www.bikedekho.com/bajaj-bikes/pulsar-rs-200/reviews', 'https://www.bikedekho.com/bajaj-bikes/pulsar-n160/reviews', 'https://www.bikedekho.com/bajaj-bikes/pulsar-220/reviews', 'https://www.bikedekho.com/bajaj-bikes/pulsar-150-ns/reviews', 'https://www.bikedekho.com/bajaj-bikes/dominar-400/reviews', 'https://www.bikedekho.com/bajaj-bikes/chetak/reviews', 'https://www.bikedekho.com/bajaj-bikes/platina/reviews', 'https://www.bikedekho.com/bajaj-bikes/platina-100/reviews', 'https://www.bikedekho.com/bajaj-bikes/dominar-250/reviews', 'https://www.bikedekho.com/bajaj-bikes/pulsar-n250/reviews', 'https://www.bikedekho.com/bajaj-bikes/avenger-160/reviews', 'https://www.bikedekho.com/bajaj-bikes/ct110/reviews', 'https://www.bikedekho.com/bajaj-bikes/ct-125x/reviews', 'https://www.bikedekho.com/bajaj-bikes/pulsar-p150/reviews', 'https://www.bikedekho.com/bajaj-bikes/pulsar-250/reviews', 'https://www.bikedekho.com/bajaj-bikes/avenger-cruise-220/reviews', 'https://www.bikedekho.com/bajaj-bikes/avenger-220-street/reviews']
    # start_urls=['https://www.bikedekho.com/tvs/raider/reviews', 'https://www.bikedekho.com/tvs/ntorq-125/reviews', 'https://www.bikedekho.com/tvs/apache-160/reviews', 'https://www.bikedekho.com/tvs/jupiter/reviews', 'https://www.bikedekho.com/tvs/apache/reviews', 'https://www.bikedekho.com/tvs/iqube-electric/reviews', 'https://www.bikedekho.com/tvs/akula-310/reviews', 'https://www.bikedekho.com/tvs/xl-100/reviews', 'https://www.bikedekho.com/tvs/ronin/reviews', 'https://www.bikedekho.com/tvs/jupiter-125/reviews', 'https://www.bikedekho.com/tvs/scooty/reviews', 'https://www.bikedekho.com/tvs/sport/reviews', 'https://www.bikedekho.com/tvs/apache-rtr-200-4v/reviews', 'https://www.bikedekho.com/tvs/apache-rtr-180/reviews', 'https://www.bikedekho.com/tvs/radeon/reviews', 'https://www.bikedekho.com/tvs/star-city-plus/reviews', 'https://www.bikedekho.com/tvs/scooty-zest/reviews']
    # start_urls=['https://www.bikedekho.com/ktm/duke-200/reviews', 'https://www.bikedekho.com/ktm/duke-390/reviews', 'https://www.bikedekho.com/ktm/rc-200/reviews', 'https://www.bikedekho.com/ktm/duke-250/reviews', 'https://www.bikedekho.com/ktm/125-duke/reviews', 'https://www.bikedekho.com/ktm/rc-390/reviews', 'https://www.bikedekho.com/ktm/rc-125/reviews', 'https://www.bikedekho.com/ktm/390-adventure/reviews', 'https://www.bikedekho.com/ktm/250-adventure/reviews', 'https://www.bikedekho.com/ktm/390-adventure-x/reviews']
    # start_urls=['https://www.bikedekho.com/yamaha/mt-15/reviews', 'https://www.bikedekho.com/yamaha/r15-v4/reviews', 'https://www.bikedekho.com/yamaha/yzf-r15-v3/reviews', 'https://www.bikedekho.com/yamaha/fz-s-fi-version-3/reviews', 'https://www.bikedekho.com/yamaha/aerox-155/reviews', 'https://www.bikedekho.com/yamaha/fz-fi-version-3/reviews', 'https://www.bikedekho.com/yamaha/ray-zr-125/reviews', 'https://www.bikedekho.com/yamaha/fascino/reviews', 'https://www.bikedekho.com/yamaha/fz-x/reviews', 'https://www.bikedekho.com/yamaha/fz-250/reviews', 'https://www.bikedekho.com/yamaha/fzs-fi-v4/reviews', 'https://www.bikedekho.com/yamaha/fzs-25/reviews']
    # start_urls=['https://www.bikedekho.com/honda/activa/reviews', 'https://www.bikedekho.com/honda/sp125/reviews', 'https://www.bikedekho.com/honda/shine/reviews', 'https://www.bikedekho.com/honda/activa-125/reviews', 'https://www.bikedekho.com/honda/dio/reviews', 'https://www.bikedekho.com/honda/unicorn-160/reviews', 'https://www.bikedekho.com/honda/sp160/reviews', 'https://www.bikedekho.com/honda/shine-100/reviews', 'https://www.bikedekho.com/honda/hness-cb350/reviews', 'https://www.bikedekho.com/honda/hornet-20/reviews', 'https://www.bikedekho.com/honda/livo/reviews', 'https://www.bikedekho.com/honda/cd-110-dream/reviews', 'https://www.bikedekho.com/honda/dio-125/reviews', 'https://www.bikedekho.com/honda/xblade/reviews', 'https://www.bikedekho.com/honda/cb200x/reviews', 'https://www.bikedekho.com/honda/cb350rs/reviews', 'https://www.bikedekho.com/honda/gold-wing/reviews', 'https://www.bikedekho.com/honda/cbr650r/reviews', 'https://www.bikedekho.com/honda/cbr1000rr-r/reviews', 'https://www.bikedekho.com/honda/cb300r/reviews', 'https://www.bikedekho.com/honda/cb500x/reviews', 'https://www.bikedekho.com/honda/cb300f/reviews', 'https://www.bikedekho.com/honda/cb650r/reviews', 'https://www.bikedekho.com/honda/crf-1100l/reviews']
    # start_urls=['https://www.bikedekho.com/hero/splendor/reviews', 'https://www.bikedekho.com/hero/hf-deluxe/reviews', 'https://www.bikedekho.com/hero/xpulse-200/reviews', 'https://www.bikedekho.com/hero/passion-pro-110/reviews', 'https://www.bikedekho.com/hero/super-splendor/reviews', 'https://www.bikedekho.com/hero/glamour-2017/reviews', 'https://www.bikedekho.com/hero/splendor-plus-xtec/reviews', 'https://www.bikedekho.com/hero/xtreme-160r/reviews', 'https://www.bikedekho.com/hero/xoom-110/reviews', 'https://www.bikedekho.com/hero/hero-passion-plus/reviews', 'https://www.bikedekho.com/hero/pleasure-2019/reviews', 'https://www.bikedekho.com/hero/maestro-edge/reviews', 'https://www.bikedekho.com/hero/destini-125/reviews', 'https://www.bikedekho.com/hero/glamour-xtec/reviews', 'https://www.bikedekho.com/hero/xtreme-160r-4v/reviews', 'https://www.bikedekho.com/hero/super-splendor-xtec/reviews', 'https://www.bikedekho.com/hero/hf-100/reviews', 'https://www.bikedekho.com/hero/xtreme-200s/reviews', 'https://www.bikedekho.com/hero/xpulse-200t/reviews', 'https://www.bikedekho.com/hero/maestro-edge-110/reviews']
    # start_urls=['https://www.bikedekho.com/suzuki/access-125/reviews', 'https://www.bikedekho.com/suzuki/hayabusa/reviews', 'https://www.bikedekho.com/suzuki/burgman-street/reviews', 'https://www.bikedekho.com/suzuki/gixxer/reviews', 'https://www.bikedekho.com/suzuki/gixxer-sf/reviews', 'https://www.bikedekho.com/suzuki/avenis/reviews', 'https://www.bikedekho.com/suzuki/v-strom-250/reviews', 'https://www.bikedekho.com/suzuki/gixxer-250/reviews', 'https://www.bikedekho.com/suzuki/gixxer250/reviews', 'https://www.bikedekho.com/suzuki/v-strom-650/reviews', 'https://www.bikedekho.com/suzuki/katana/reviews']
    # start_urls=['https://www.bikedekho.com/jawa-motorcycles/42-bobber/reviews', 'https://www.bikedekho.com/jawa-motorcycles/42/reviews', 'https://www.bikedekho.com/jawa-motorcycles/jawa-perak/reviews', 'https://www.bikedekho.com/jawa-motorcycles/jawa-300/reviews', 'https://www.bikedekho.com/jawa-motorcycles/jawa-forty-two/reviews']
    # start_urls=['https://wcww.bikedekho.com/ducati/panigale-v4/reviews', 'https://www.bikedekho.com/ducati/streetfighter-v4/reviews', 'https://www.bikedekho.com/ducati/monster/reviews', 'https://www.bikedekho.com/ducati/scrambler/reviews', 'https://www.bikedekho.com/ducati/diavel-v4/reviews', 'https://www.bikedekho.com/ducati/panigale-v2/reviews', 'https://www.bikedekho.com/ducati/supersport/reviews', 'https://www.bikedekho.com/ducati/desertx/reviews', 'https://www.bikedekho.com/ducati/multistrada-950/reviews', 'https://www.bikedekho.com/ducati/multistrada-v2/reviews', 'https://www.bikedekho.com/ducati/hypermotard-950/reviews', 'https://www.bikedekho.com/ducati/desert-sled/reviews', 'https://www.bikedekho.com/ducati/diavel-1260/reviews', 'https://www.bikedekho.com/ducati/multistrada-v4/reviews', 'https://www.bikedekho.com/ducati/xdiavel/reviews', 'https://www.bikedekho.com/ducati/streetfighter-v2/reviews', 'https://www.bikedekho.com/ducati/scrambler-1100/reviews']
    # start_urls=['https://www.bikedekho.com/kawasaki/ninja-zx-10r/reviews', 'https://www.bikedekho.com/kawasaki/ninja-h2/reviews', 'https://www.bikedekho.com/kawasaki/2020-z900/reviews', 'https://www.bikedekho.com/kawasaki/ninja/reviews', 'https://www.bikedekho.com/kawasaki/ninja-400/reviews', 'https://www.bikedekho.com/kawasaki/ninja-1000/reviews', 'https://www.bikedekho.com/kawasaki/2020-ninja-650/reviews', 'https://www.bikedekho.com/kawasaki/w175/reviews', 'https://www.bikedekho.com/kawasaki/2020-z650/reviews', 'https://www.bikedekho.com/kawasaki/zh2/reviews', 'https://www.bikedekho.com/kawasaki/vulcan-s/reviews', 'https://www.bikedekho.com/kawasaki/versys-650/reviews', 'https://www.bikedekho.com/kawasaki/kx-100/reviews', 'https://www.bikedekho.com/kawasaki/klx-140-g/reviews', 'https://www.bikedekho.com/kawasaki/kx112/reviews', 'https://www.bikedekho.com/kawasaki/klx230rs/reviews', 'https://www.bikedekho.com/kawasaki/versys-1000/reviews', 'https://www.bikedekho.com/kawasaki/kx-250-f/reviews', 'https://www.bikedekho.com/kawasaki/w800/reviews', 'https://www.bikedekho.com/kawasaki/kx-450f/reviews', 'https://www.bikedekho.com/kawasaki/klx-110/reviews', 'https://www.bikedekho.com/kawasaki/z650rs/reviews', 'https://www.bikedekho.com/kawasaki/z900rs/reviews', 'https://www.bikedekho.com/kawasaki/klx-450r/reviews', 'https://www.bikedekho.com/kawasaki/kx-65/reviews']
    # start_urls=['https://www.bikedekho.com/benelli/trk-502/reviews', 'https://www.bikedekho.com/benelli/imperiale-400/reviews', 'https://www.bikedekho.com/benelli/502-c/reviews', 'https://www.bikedekho.com/benelli/trk-251/reviews', 'https://www.bikedekho.com/benelli/leoncino/reviews']
    
    # strat_urls=['https://www.bikedekho.com/triumph/speed-400/reviews', 'https://www.bikedekho.com/triumph/street-triple/reviews', 'https://www.bikedekho.com/triumph/trident/reviews', 'https://www.bikedekho.com/triumph/rocket-3/reviews', 'https://www.bikedekho.com/triumph/tiger-900/reviews', 'https://www.bikedekho.com/triumph/street-twin/reviews', 'https://www.bikedekho.com/triumph/tiger-sport-660/reviews', 'https://www.bikedekho.com/triumph/speed-triple-1200/reviews', 'https://www.bikedekho.com/triumph/speed-twin/reviews', 'https://www.bikedekho.com/triumph/tiger-850/reviews', 'https://www.bikedekho.com/triumph/street-scrambler/reviews', 'https://www.bikedekho.com/triumph/bonneville/reviews', 'https://www.bikedekho.com/triumph/bonneville-bobber/reviews', 'https://www.bikedekho.com/triumph/speedmaster/reviews', 'https://www.bikedekho.com/triumph/bonneville-t100/reviews', 'https://www.bikedekho.com/triumph/tiger-1200/reviews']
    # strat_urls=['https://www.bikedekho.com/indian/scout-bobber/reviews', 'https://www.bikedekho.com/indian/ftr-1200/reviews', 'https://www.bikedekho.com/indian/challenger/reviews', 'https://www.bikedekho.com/indian/roadmaster/reviews', 'https://www.bikedekho.com/indian/scout/reviews', 'https://www.bikedekho.com/indian/pursuit/reviews', 'https://www.bikedekho.com/indian/scoute-rogue/reviews', 'https://www.bikedekho.com/indian/chieftain-dark-horse/reviews', 'https://www.bikedekho.com/indian/springfield-dark-horse/reviews', 'https://www.bikedekho.com/indian/chief-bobber-dark-horse/reviews', 'https://www.bikedekho.com/indian/super-chief-limited/reviews', 'https://www.bikedekho.com/indian/chief-dark-horse/reviews', 'https://www.bikedekho.com/indian/springfield/reviews', 'https://www.bikedekho.com/indian/chieftain-elite/reviews', 'https://www.bikedekho.com/indian/chieftain-limited/reviews']
    # strat_urls=['https://www.bikedekho.com/bmw/s1000rr/reviews', 'https://www.bikedekho.com/bmw/g-310-r/reviews', 'https://www.bikedekho.com/bmw/g-310-rr/reviews', 'https://www.bikedekho.com/bmw/g-310-gs/reviews', 'https://www.bikedekho.com/bmw/r-1250-gs/reviews', 'https://www.bikedekho.com/bmw/c-400-gt/reviews', 'https://www.bikedekho.com/bmw/r-1250-gs-adventure/reviews', 'https://www.bikedekho.com/bmw/m-1000-rr/reviews', 'https://www.bikedekho.com/bmw/f-850-gs/reviews', 'https://www.bikedekho.com/bmw/k-1600/reviews', 'https://www.bikedekho.com/bmw/f-900-r/reviews', 'https://www.bikedekho.com/bmw/r-nine-t/reviews', 'https://www.bikedekho.com/bmw/f-850-gs-adventure/reviews', 'https://www.bikedekho.com/bmw/r-18/reviews', 'https://www.bikedekho.com/bmw/f-900-xr/reviews', 'https://www.bikedekho.com/bmw/r-18-transcontinental/reviews', 'https://www.bikedekho.com/bmw/r-nine-t-scrambler/reviews', 'https://www.bikedekho.com/bmw/k-1600-b/reviews', 'https://www.bikedekho.com/bmw/2020-s-1000-xr/reviews', 'https://www.bikedekho.com/bmw/k-1600-grand-america/reviews', 'https://www.bikedekho.com/bmw/r-1250-rt/reviews', 'https://www.bikedekho.com/bmw/2021-s1000r/reviews', 'https://www.bikedekho.com/bmw/r-1250-r/reviews']
    strat_urls=['https://www.bikedekho.com/aprilia/sr-160-bs6/reviews', 'https://www.bikedekho.com/aprilia/sr-125/reviews', 'https://www.bikedekho.com/aprilia/rs-660/reviews', 'https://www.bikedekho.com/aprilia/rsv4/reviews', 'https://www.bikedekho.com/aprilia/sxr160/reviews', 'https://www.bikedekho.com/aprilia/storm-125/reviews', 'https://www.bikedekho.com/aprilia/sxr-125/reviews', 'https://www.bikedekho.com/aprilia/tuono-v4/reviews', 'https://www.bikedekho.com/aprilia/tuono-660/reviews']
    # strat_urls=['https://www.bikedekho.com/yezdi-motorcycles/cruiser/reviews', 'https://www.bikedekho.com/yezdi-motorcycles/adventure/reviews', 'https://www.bikedekho.com/yezdi-motorcycles/roadking/reviews']


    # start_urls=['https://www.bikedekho.com/harley-davidson/x440/reviews', 'https://www.bikedekho.com/harley-davidson/fat-boy/reviews', 'https://www.bikedekho.com/harley-davidson/nightster/reviews', 'https://www.bikedekho.com/harley-davidson/custom-1250/reviews', 'https://www.bikedekho.com/harley-davidson/fat-bob/reviews', 'https://www.bikedekho.com/harley-davidson/pan-america-1250/reviews', 'https://www.bikedekho.com/harley-davidson/street-glide/reviews', 'https://www.bikedekho.com/harley-davidson/road-glide-special/reviews', 'https://www.bikedekho.com/harley-davidson/heritage-softail-classic/reviews']




    def parse(self, response):
        average_ratings=response.css('span.ratingvalue::text').get()
        review_links=response.css('h3 a::attr(href)').getall()
        for link in review_links:
            url='https://www.bikedekho.com'
            full_url='https://www.bikedekho.com'+link
            print(full_url)
            yield response.follow(full_url, callback=self.parse_reviews)

        # next_page_url=response.css('')
        next_page_href=response.xpath('/html/body/div[2]/div/div[1]/div/div[1]/main/div/div[1]/section[2]/div/div[3]/div/div/div/ul/li[7]/a/@href').get()
        if next_page_href is not None:
            full_href='https://www.bikedekho.com'+next_page_href
            yield response.follow(full_href, callback=self.parse)

            
            

    def parse_reviews(self, response):
        user_stars=0
        for num in range(1, 6):
            css_selector = f'section.clearfix.userDetail.shadow24.marginBottom20 span.stars.stars{num}.icon-star-full-fill'
            x=response.css(css_selector).get()
            if x is not None:
                user_stars=user_stars+1


        yield{
            
            'Varient_Name':response.css('div.title a::text').get(),
            'Average_stars':response.css('span.ratingvalue::text').get(),
            'Review_title':response.css('h1 ::text').get(),
            'User_rating':user_stars,
            'Review_description': response.css('p.contentheight::text').get()

        }
    
        
        
             
